/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddRocketDialog: typeof import('./src/components/AddRocketDialog.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    DetailField: typeof import('./src/components/DetailField.vue')['default']
    LoadingGrid: typeof import('./src/components/LoadingGrid.vue')['default']
    RocketCard: typeof import('./src/components/RocketCard.vue')['default']
    RocketFilterBar: typeof import('./src/components/RocketFilterBar.vue')['default']
    RocketImage: typeof import('./src/components/RocketImage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StateMessage: typeof import('./src/components/StateMessage.vue')['default']
  }
}
